### ISSUE TITLE
initializeApprovalTestsForGoogleTests

### ISSUE THREAD

**Issue by alastairUK** [approvals/ApprovalTests.cpp#10]
I believe this function should be marked 'inline' otherwise you get 

error LNK2005: "void __cdecl initializeApprovalTestsForGoogleTests(void)" (?initializeApprovalTestsForGoogleTests@@YAXXZ) already defined in ApprovalTests.obj

**Comment by claremacrae** [comment]
Thanks for pointing this out. It's now fixed...
If you are stilling having trouble, please let us know.
