### ISSUE TITLE
'pbclip not found' when using Clipboard Reporter on older mac

### ISSUE THREAD

**Issue by emilybache** [approvals/ApprovalTests.cpp#109]
When I use the clipboard reporter, tests crash with this message:

'sh: pbclip: command not found'

I'm using a slightly older mac, running os version 10.12.6,  Sierra.

I set the default reporter to be a ClipboardReporter according to the documentation, this is my main.cpp:

#define APPROVALS_DOCTEST
#include "ApprovalTests.hpp"

#include <memory>
auto defaultReporterDisposer =
        Approvals::useAsDefaultReporter(std::make_shared<ClipboardReporter>());

When I look on the command line, I have commands 'pbcopy' and 'pbpaste' but not 'pbclip'. I wonder if my mac os is too old to have pbclip?

**Comment by emilybache** [comment]
Sorry about this, I updated to the latest version of Approval tests and the problem vanished.

**Comment by claremacrae** [comment]
Hi @emilybache - you beat me to it. This was fixed in 
https://github.com/approvals/ApprovalTests.cpp/releases/tag/v.7.0.0
