### ISSUE TITLE
doctest support?

### ISSUE THREAD

**Issue by lichray** [approvals/ApprovalTests.cpp#11]
https://github.com/onqtam/doctest

**Comment by isidore** [comment]
this should be very possible, but would need a doctest expert to pair with. Usually this is a 30-40 minute thing with an expert. Are you that person?

**Comment by claremacrae** [comment]
If doing this, I'd suggest first moving the Catch2, GoogleTest and Okra implementations in to a sub-directory, as I hope that this list of supported frameworks will keep on growing...
See https://github.com/approvals/ApprovalTests.cpp/tree/master/ApprovalTests

It looks like doctest does have the ability to listen out for new tests:
https://github.com/onqtam/doctest/blob/master/examples/all_features/reporters_and_listeners.cpp

**Comment by zhihaoy** [comment]
> this should be very possible, but would need a doctest expert to pair with. Usually this is a 30-40 minute thing with an expert. Are you that person?

I only have time to use it :)

> It looks like doctest does have the ability to listen out for new tests:
> https://github.com/onqtam/doctest/blob/master/examples/all_features/reporters_and_listeners.cpp

And `DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN`, `DOCTEST_REGISTER_REPORTER`.

**Comment by claremacrae** [comment]
Hi, no worries... Thanks very much for the suggestion - and for letting us know about another testing framework.

I really like its promise of faster build times!

**Comment by claremacrae** [comment]
Things that I'm aware of that we still need to do

* [ ] Remove `using namespace doctest;` in `ApprovalTests/integrations/doctest/DocTestApprovals.h`
* [ ] Fix the stomping on command-line arguments in our doctest main - depends on https://github.com/onqtam/doctest/issues/257
* [ ] Fix compiler warnings:

/cygdrive/d/Users/Clare/Documents/Programming/github/ApprovalTests/ApprovalTests.cpp/ApprovalTests/integrations/doctest/DocTestApprovals.h:16:8: warning: 'DocTestApprovalListener' has a field 'DocTestApprovalListener::<anonymous>' whose type uses the anonymous namespace [-Wsubobject-linkage]
 struct DocTestApprovalListener : ConsoleReporter
        ^~~~~~~~~~~~~~~~~~~~~~~
/cygdrive/d/Users/Clare/Documents/Programming/github/ApprovalTests/ApprovalTests.cpp/ApprovalTests/integrations/doctest/DocTestApprovals.h:16:8: warning: 'DocTestApprovalListener' has a base 'doctest::{anonymous}::ConsoleReporter' whose type uses the anonymous namespace [-Wsubobject-linkage]
[ 66%] Linking CXX executable ApprovalTests_DocTest_Tests.exe
[100%] Built target ApprovalTests_DocTest_Tests

* [ ] Re-enable treating warnings as errors in `ApprovalTests_DocTest_Tests/CMakeLists.txt`
* [ ] Add doctest support to all our documentation

**Comment by claremacrae** [comment]
This is now released! 
See https://github.com/approvals/ApprovalTests.cpp/releases/tag/v.3.5.0
