### ISSUE TITLE
Add support for initializer lists to verifyAll

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp#146]
Suggested by @JayBazuzi

**Comment by alepez** [comment]
Hi Clare, I've [experimented with initializer list](https://github.com/approvals/ApprovalTests.cpp/compare/master...alepez:146-initializer-lists) and it seems to work. We can schedule a pair-programming session if you wish.

**Comment by claremacrae** [comment]
Hi Alessandro, a pairing session would be great - thanks for looking at this!
