### ISSUE TITLE
Passing tests don't register in Catch2 and other test frameworks

### ISSUE THREAD

**Issue by barneydellar** [approvals/ApprovalTests.cpp#148]
If I have a test such as 

`ApprovalTests::Approvals::verify("Hello World");`

then failures are reported correctly in Catch2, but when it passes, Catch2 reports that no asserts were encountered:

`assertions: - none -`

This is confusing :-(

**Comment by claremacrae** [comment]
Yes, so far our “how to wrap a test framework” does not include an abstraction for “tell the framework that a test has passed.”

https://approvaltestscpp.readthedocs.io/en/latest/generated_docs/SupportingNewTestFramework.html

I think we would have to some kind of extension point that triggers "test has passed" - and then hook up each of our existing test framework integrations to call that.

I do agree it would be nice to implement this.

**Comment by claremacrae** [comment]
If we could also make failing tests register in Catch2, then that project's `--break` command line argument would be really useful, to allow break on failure when run in a debugger.

**Comment by claremacrae** [comment]
This is done, and will be included in the upcoming release.

Thanks for the suggestion, @barneydellar
