### ISSUE TITLE
Add vcpkg to our release process

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp#186]
We’ll need to create a PR to update the vcpkg port, like we already do for Conan.

The original PR for adding vcpkg support is: 
[#18338 · microsoft/vcpkg · GitHub](https://github.com/microsoft/vcpkg/pull/18338)

The current content of our port is: 
[vcpkg/ports/approval-tests-cpp at master](https://github.com/microsoft/vcpkg/tree/master/ports/approval-tests-cpp)

Note that we won’t need to accumulate data for successive releases in the two port files - we will overwrite it, and then run some script to update some indexes.

**Comment by isidore** [comment]
believe this is done with python scripts now
