### ISSUE TITLE
Allow users to detect Approval Test version in code

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp#40]
In #37 it was really helpful to be able to write code that was able to detect the doctest version number, to be able to support more than one doctest version.

The relevant doctest code is:

```cpp
// =================================================================================================
// == VERSION ======================================================================================
// =================================================================================================

#define DOCTEST_VERSION_MAJOR 2
#define DOCTEST_VERSION_MINOR 3
#define DOCTEST_VERSION_PATCH 5
#define DOCTEST_VERSION_STR "2.3.5"

#define DOCTEST_VERSION                                                                            \
    (DOCTEST_VERSION_MAJOR * 10000 + DOCTEST_VERSION_MINOR * 100 + DOCTEST_VERSION_PATCH)
```

Can we do the corresponding thing in Approval Tests too?

This would involve changing the release script, to set the values automatically.

**Comment by claremacrae** [comment]
Before doing this, it would be worth looking at Catch2's release scripts, which are in Python and really nice and clean, for example:

https://github.com/catchorg/Catch2/blob/master/scripts/minorRelease.py

You don't have to even work out what the next version number will be. You just say "I'm doing a minor release" (or major, or patch) and it takes care of all the appropriate incrementation.

**Comment by dheater** [comment]
How about using `CMake` to generate the version number?
https://cmake.org/cmake/help/latest/guide/tutorial/index.html#adding-a-version-number-and-configured-header-file

**Comment by claremacrae** [comment]
> How about using `CMake` to generate the version number?
> https://cmake.org/cmake/help/latest/guide/tutorial/index.html#adding-a-version-number-and-configured-header-file

That's one possibility...

We'd still need to get the version number in to CMake in the first place, and this script updates the version number in various places:
https://github.com/approvals/ApprovalTests.cpp/blob/master/build/build_hpp.sh

So also a possibility is to make `build_hpp.sh` to edit in the version number directly...

**Comment by dheater** [comment]
Yeah. Probably makes more sense to go direct with `build_hpp.sh` since there are several other things being modified.

**Comment by claremacrae** [comment]
This is now implemented, using these steps:

* [ApprovalTests/ApprovalTestsVersion.h](https://github.com/approvals/ApprovalTests.cpp/blob/master/ApprovalTests/ApprovalTestsVersion.h) is machine-generated during each release, and contains the version number
* That file is included during development in [ApprovalTests/ApprovalTests.hpp](https://github.com/approvals/ApprovalTests.cpp/blob/master/ApprovalTests/ApprovalTests.hpp)
* The header Blocker.h seems to always be include first in the single header, at least going back to v.3.3.0, so by including this new header in Blocker.h, we ensure that the information from this file will always appear at the top of the generated single-header file.

The generated code looks like this:

```c++
#ifndef APPROVALTESTS_CPP_APPROVALTESTSVERSION_H
#define APPROVALTESTS_CPP_APPROVALTESTSVERSION_H

#define APPROVALTESTS_VERSION_MAJOR 8
#define APPROVALTESTS_VERSION_MINOR 0
#define APPROVALTESTS_VERSION_PATCH 0
#define APPROVALTESTS_VERSION_STR "8.0.0"

#define APPROVALTESTS_VERSION                                                  \
    (APPROVALTESTS_VERSION_MAJOR * 10000 + APPROVALTESTS_VERSION_MINOR * 100 + \
     APPROVALTESTS_VERSION_PATCH)

#endif //APPROVALTESTS_CPP_APPROVALTESTSVERSION_H
```
