### ISSUE TITLE
Boost Test Support

### ISSUE THREAD

**Issue by jwillikers** [approvals/ApprovalTests.cpp#41]
I think it would be worth-while to support the Boost Test framework out-of-the-box. Is this plausible?

**Comment by claremacrae** [comment]
Thanks!

I was going to ask if you would be likely to use it, but this is maybe the 4th or 5th time it's been mentioned, so I think there is likely enough use for it to be worthwhile trying to do...

Might you be willing to work together, via screen-sharing, at some point to pair-program and try implementing it?

**Comment by claremacrae** [comment]
This is what needs to be possible in a test framework, in order for us to support it in Approval Tests:

https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/SupportingNewTestFramework.md#top

**Comment by claremacrae** [comment]
Latest Boost Test framework reference:

https://www.boost.org/doc/libs/1_71_0/libs/test/doc/html/index.html

**Comment by athrun22** [comment]
Thanks for the links. I'll look into it a bit more when I have time and then touch base again about the screen share next week, if not earlier.

**Comment by claremacrae** [comment]
Brilliant - thank you very much.

**Comment by claremacrae** [comment]
Hi @jwillikers - are you still interested in this? We've started work on it, and in a few days' time, it would be good to get feedback from someone who knows Boost Test *and* who knows Approval Tests...

**Comment by jwillikers** [comment]
Hello @claremacrae, I should be able to take a look in the next couple of days. Is there a branch with the current work I can take a look at?

**Comment by claremacrae** [comment]
Thanks @jwillikers ...

Yes, it's very much early days, and with a very simple sketch, checking that we can get the filename.

The branch is boost_test_support

And here's the current code:

https://github.com/approvals/ApprovalTests.cpp/tree/391a188404c20ba4b9ffc1399bbb7817c126ae5e/tests/Boost_Tests

I've started a PR - #119 - so we have an easy way to see the changes, and add and manage comments...

**Comment by claremacrae** [comment]
> I've started a PR - #119 - so we have an easy way to see the changes, and add and manage comments...

@jwillikers and added a couple of comments in the PR itself about things I'm unsure of....

**Comment by claremacrae** [comment]
We ended up not pulling in the boost test headers, and documenting that the user needs to do this.

This simplified our work considerably.

We are about to release this in v.8.6.0 - thanks for the help, @jwillikers
