### ISSUE TITLE
More flexibilty for adding custom merge tools

### ISSUE THREAD

**Issue by jwillikers** [approvals/ApprovalTests.cpp#43]
Trying to add support for [Sublime Merge](https://www.sublimemerge.com/docs/command_line) was very difficult because it requires the command-line argument "mergetool" before the two merged files and passing this in as the second argument to DiffInfo doesn't seem to end up in the command when it is sent to the system. Additionally, the merge tool has a "--no-wait" option which must be used instead of running it as a daemon with "&". Running the Sublime Merge mergetool as a daemon leads to diffs being opened twice.

The inheritance hierarchy was very difficult for me to figure out. An easier way to add a merge tool would be wonderful. Perhaps using a unique placeholder for each of the received and approved files in a string or list of string, the specific command-line call could be structured as needed. An option for whether to run as a daemon or not would also be handy. Thanks.

Below is the code I used to add support for Sublime Merge. I have only tested it on mac and Windows at the moment.
```cpp
#pragma once
#include <string>
#include <utility>
#include <vector>
#include <ApprovalTests/ApprovalTests.hpp>

namespace ApprovalTests {

namespace DiffPrograms {

namespace Mac {
APPROVAL_TESTS_MACROS_ENTRY(SUBLIME_MERGE,
                            DiffInfo("/Applications/Sublime Merge.app/Contents/SharedSupport/bin/smerge", Type::TEXT))
}

namespace Linux {
APPROVAL_TESTS_MACROS_ENTRY(SUBLIME_MERGE, DiffInfo("smerge", Type::TEXT))
}

namespace Windows {
APPROVAL_TESTS_MACROS_ENTRY(SUBLIME_MERGE, DiffInfo("{ProgramFiles}Sublime Merge\\smerge.exe", Type::TEXT))
}

}

class SublimeMergeSystemLauncher
    :
        public CommandLauncher {
public:
  static bool exists(const std::string &command) {
    bool foundByWhich = false;
    if (!SystemUtils::isWindowsOs()) {
      std::string which = "which " + command + " > /dev/null 2>&1";
      int result = system(which.c_str());
      foundByWhich = (result == 0);
    }
    return foundByWhich || FileUtils::fileExists(command);
  }

  bool launch(std::vector<std::string> argv) override {
    if (!exists(argv.front())) {
      return false;
    }

    std::string command = std::accumulate(argv.begin(),
                                          argv.end(),
                                          std::string(""),
                                          [](const std::string &a, const std::string &b) {
                                            return a + " " + "\"" + b + "\"";
                                          });
    std::string launch = SystemUtils::isWindowsOs() ? ("start \"\" " + command) : command;
    system(launch.c_str());
    return true;
  }
};

class SublimeMergeReporter
    :
        public Reporter {
private:
  std::string m_command;
  mutable SublimeMergeSystemLauncher m_launcher;

public:
  explicit SublimeMergeReporter(std::string command)
      : m_command(std::move(command)) {}

  [[nodiscard]] bool report(std::string received, std::string approved) const override;
};

bool SublimeMergeReporter::report(std::string received, std::string approved) const {
  FileUtils::ensureFileExists(approved);
  return m_launcher.launch({m_command, "mergetool", "--no-wait", received, approved, "-o", approved});
}
```

**Comment by claremacrae** [comment]
Sorry about DiffInfo ignoring its arguments. It's noted in our to_do.txt file, from before anyone was using git issues for this project...

Note to self:

* Create an issue for the DiffInfo bug
* And treat this one as the new feature, of easier support for adding user-added reporters

And wow, yes, that is a lot of code to work out how to write.

**Comment by claremacrae** [comment]
In case it helps in the meantime, I have some possibly related code in:

https://github.com/claremacrae/ApprovalTests.cpp.Nursery

This is a launcher that doesn't open programs in the background, that is, doesn't use &
https://github.com/claremacrae/ApprovalTests.cpp.Nursery/blob/master/ApprovalTestsNursery/ForegroundSystemLauncher.h

But it still wouldn't solve the problem of DiffInfo args being discarded...

**Comment by claremacrae** [comment]
@lp55 also made the point today, when we were talking about the changes in #57, that the edits needed to add new external diff reporters are quite verbose and split over multiple files, which isn't so convenient for longer term maintenance...

**Comment by claremacrae** [comment]
> Sorry about DiffInfo ignoring its arguments. It's noted in our to_do.txt file, from before anyone was using git issues for this project...
> 
> Note to self:
> 
>     * Create an issue for the DiffInfo bug

Done - see #82

**Comment by claremacrae** [comment]
I was thinking about the scenarios in which people might want to customise the reporter - just noting it here, in case it helps with planning or documenting work on this issue:

* Don't like the first reporter found my Approvals on my machine - want to use a different one
* The tool I want to use is not supported by Approvals
* The tool I want to use is in a location not recognised by Approvals
* I want to change the tool used without recompiling the test program

**Comment by claremacrae** [comment]
This is mainly completed - we are still missing the option to run in the foreground. As that's covered by #98, we're closing this.

Documentation will be coming on how to use this shortly - see https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/how_tos/HowToUseACustomReporter.md

**Comment by claremacrae** [comment]
We also documented the steps required to add a new diff tool to the ApprovalTests.cpp code: https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/how_tos/SubmitANewReporterToApprovalTests.md#top
