### ISSUE TITLE
Approvals::verify fails my test with an appended '\n'

### ISSUE THREAD

**Issue by curtnichols** [approvals/ApprovalTests.cpp#50]
* I have a pre-baked approval file on disk.
* I am generating the "received" contents into a `std::string`, which is terminated by a `'\n'`.
* I am passing that `std::string` into `Approvals::verify`, which fails due to a second(!) trailing `'\n'` now appearing on my "received" content.
* It appears that `StringWriter::Write(std::ostream &)` is determined to add a `'\n'`:

```
    void Write( std::ostream &out ) const
    {
        out << s << "\n";
    }
```

This causes my call to `verify` to fail. So I wonder:

**Should `Write` be modifying my content?**

**Comment by claremacrae** [comment]
@curtnichols 

That's a very fair question. I don't think we considered people who might have pre-created approval files, and for whom the extra character written out might be a problem.

If we were to change the behaviour of StringWriter, we would break a whole load of existing tests, so this will need some thought.

An idea for a temporary workaround: we recently made it quite easy to supply custom writer implementation, so perhaps you could try supplying your own writer class that didn't add the extra newline?

There is documentation here: https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/Writers.md#top

**Comment by curtnichols** [comment]
I might try that.

Also, I need to look into writing the "received" file myself, as I'm generating it with an external program that can easily save to file itself. I suspect that might look like a custom Writer that can format the raw data.

**Comment by curtnichols** [comment]
`verifyExistingFile` sent me down a weird path, with an empty `.approved.1` file being generated. Creating a custom writer is working nicely.

For context, the code under test is being executed from within the approval tests, the external program is just for converting binary image files into something diff-able.

**Comment by curtnichols** [comment]
Thanks, I don't think I need anything more out of this issue.
