### ISSUE TITLE
Directory separators handled incorrectly on Windows with Clang

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp#59]
From @lp55:

I found a bug in ApprovalTests. Clang provides the location information with unix directory separators, even on Windows (I get something like this: c/folder/main.cpp), which the Approval Tests code for handling filesystem doesn't account for.

I can patch that, but I think it would be better for Approval Tests to offload that responsibility for a specialized library. This seems like a good option: https://github.com/gulrak/filesystem. It raise Approval Tests C++ standard requirement, and makes uses of std::filesystem if available. What do you think?

**Comment by claremacrae** [comment]
Thanks for letting me know about this - I'll have a go at reproducing it..

Any extra info that you could provide about how your build was set up would be really helpful...

We already have code for something like this with (I think) Mingw and Cygwin builds, which all vary in how they handle file paths and launching processes.

So before taking on another dependency, it would be worth looking at whether the fixes we have for those platforms can be generalised in any way to cover clang on Windows as well.

I think this also means it's time to set up a Windows/Clan CI build too...

**Comment by lp55** [comment]
My build was set-up using visual studio with the clang_cl_x64 environment. I used the source_location functionality (__builtin_FILE()) and the path provided was in unix style. ApprovalTests then creates a file with a name like this (on the binary's folder):

C__Folder_main.test0.approved

The patch is easy to make. This:

```cpp
    static std::string getDirectorySeparator()
    {
        return isWindowsOs() ? "\\" : "/";
    }

can become this:

```cpp
    static std::string getDirectorySeparator()
    {
#if defined(__clang__)
        return "/";
#else
        return isWindowsOs() ? "\\" : "/";
#endif
    }
```

   But I've seen cases were paths come with \\ and / (past experience - don't have a code example now). To account for this, a more robust solution would be required to be implemented and tested against these types of weird scenarios, that differ depending on OS and compiler. That reason why I recommended the [Filesystem](https://github.com/gulrak/filesystem) lib. It's well tested (96% coverage), source compatible with std::filesystem (which enable for a smooth transition on the future), handles UTF-8 and would allow for removal of code from Approval Tests (less is better :) ).
   Another option would be to create a filesystem header with just the functions Approval Tests needs. Seems it only needs exists, path, stem and extension functions, which can make for a small header.
   What do you think?

**Comment by claremacrae** [comment]
I've tried reproducing this with the following:

1. Update to latest Visual Studio 2019
1. Install "C++ Clang tools for Windows (9.0.0 - x64/x86)
1. Launch Visual Studio
1. File > Open > Open Folder
1. Select my clone of Approval Tests.cpp and open it
1. Select "Manage Configurations" (from a drop-down in a toolbar)
1. Click the green "+"
1. Add "x64-Claren-Release"
1. Save the CMakeSettings.json file
1. Set the Startup Program to be DocTest_Tests.exe
1. Run

I then get output beginning with this:

```
[doctest] doctest version is "2.3.5"
[doctest] run with "--help" for options
===============================================================================
..\..\..\tests\DocTest_Tests\ApprovalTestTests.cpp(7):
TEST CASE:  YouCanUseAWriter

..\..\..\tests\DocTest_Tests\ApprovalTestTests.cpp(7): ERROR: test case THREW exception: Unable to create directory: ..\..\..\tests\DocTest_Tests\approval_tests\

===============================================================================
..\..\..\tests\DocTest_Tests\ApprovalTestTests.cpp(16):
TEST CASE:  YouCanSpecifyYourFileExtension

..\..\..\tests\DocTest_Tests\ApprovalTestTests.cpp(16): ERROR: test case THREW exception: Unable to create directory: ..\..\..\tests\DocTest_Tests\approval_tests\
```

This looks like it may be the same problem as is logged in #55

**Comment by claremacrae** [comment]
Hi @lp55 

I don't think I've managed to reproduce this - when you have time, please could you give me the steps to reproduce it?

Looking at #29 it does seem that someone has previously been able to use this project with clang-cl - so I'm wondering what's different either with Visual Studio these days, or perhaps your set up now?

Googling also didn't leave me confident in what installer exactly to use for clang_cl_x64...

**Comment by lp55** [comment]
Hi Clare,

    Github doesn't allow me to attach files, so I'm sending you this 
email with an example. The ApprovalTests.v.6.0.0.hpp is patched with ut 
support and the clang filepath fix.

Cheers,

Luiz

A 2019-12-19 10:57, Clare Macrae escreveu:

**Comment by claremacrae** [comment]
Hi Luiz

Thanks - what would you like me to do with this file?

Clare

**Comment by claremacrae** [comment]
We added a help message in the v.7.0.0 release that points to this page - so hopefully if people see this problem, it will be easier to diagnose.

https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/TroubleshootingMisconfiguredBuild.md#top

Leaving this open, as the issue itself has not been addressed.

**Comment by claremacrae** [comment]
Closing, as this is more than a year old, there have been no further reports, and we do have [CI running the tests in Visual
 Studio with clang](https://github.com/approvals/ApprovalTests.cpp/runs/2283541898?check_suite_focus=true).

So this is very likely to be correct.
