### ISSUE TITLE
Boost ut include path is non-standard

### ISSUE THREAD

**Issue by athrun22** [approvals/ApprovalTests.cpp#65]
In UTApprovals.h, the ```#include <ut.hpp>``` should be ```#include <boost/ut.hpp>```. Users of Boost ut are expected to include the ut header using ```boost/ut.hpp``` as can be seen in the [tutorial](https://github.com/boost-experimental/ut#tutorial). The ```ut.hpp```  header will almost certainly not be found by the user's compiler without explicitly modifying the searched include directories.

**Comment by claremacrae** [comment]
@athrun22 Hi, hopefully this is fixed now... Thanks for reporting it!

**Comment by athrun22** [comment]
@claremacrae, the changes look great 👍 I'll confirm that it works tomorrow.

**Comment by athrun22** [comment]
I just confirmed that the fix works. 👍Thank you, @claremacrae.
