### ISSUE TITLE
Boost ut Change in Template Parameters

### ISSUE THREAD

**Issue by athrun22** [approvals/ApprovalTests.cpp#66]
Boost ut removed the template parameter ```TLocation``` in a recent [commit](https://github.com/boost-experimental/ut/commit/94220e8c95b323349bfd94ef30b2568916fb1421#diff-04c6e90faac2675aa89e2176d2eec7d8). This template parameter will need to be removed from functions in [UTApprovals.h](https://github.com/approvals/ApprovalTests.cpp/blob/master/ApprovalTests/integrations/ut/UTApprovals.h) to maintain compatibility with the next Boost ut release.

**Comment by athrun22** [comment]
Removing the template parameter ```TLocation``` from [UTApprovals.h](https://github.com/approvals/ApprovalTests.cpp/blob/master/ApprovalTests/integrations/ut/UTApprovals.h) does indeed solve the issue and Approval Tests once again builds using the most recent [commit](https://github.com/boost-experimental/ut/commit/8004290d195b08eda531eb015ddcda2e11d41ce9) of Boost ut at this time.

**Comment by claremacrae** [comment]
@krzysztof-jusiak Please note this. Can the removed TLocation parameter be reinstated to fix the ApprovalTests.cpp integration, for example?

**Comment by krzysztof-jusiak** [comment]
I will prepare a MR for ApprovalTests with a fix, `TLocation` template parameter is not needed anymore, `source_location` is used instead.

**Comment by claremacrae** [comment]
This was fixed in #67 - thanks Krys.

**Comment by athrun22** [comment]
Thanks @claremacrae  and @krzysztof-jusiak!
