### ISSUE TITLE
Create a namespaced CMake target for ApprovalTests

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp#75]
For details, see the really clear explanation by @athrun22 in: https://github.com/approvals/ApprovalTests.cpp/issues/69#issuecomment-570188091

**Comment by claremacrae** [comment]
Here's the explanation, copied from the original issue:

@claremacrae, a namespaced CMake target for ApprovalTests would be good to create before this documentation is done. By adding an aliased CMake target for ApprovalTests that prefixes a namespace, users can switch between using an installed version of the library - if support for ```find_package``` is added  - and ```add_subdirectory``` / ```FetchContent``` without having to change the ApprovalTests library name. That's dense when I put it into words 🙄

An example might make this more clear. 🤔
The following example links to a hypothetically installed version of ApprovalTests, though this not supported at the moment.
```cmake
# Use an installed version of ApprovalTests
find_package(ApprovalTests 7.0.0 REQUIRED)
add_executable(my-test PRIVATE main.cpp)
# According to standard practice, imported targets are prefixed with a namespace
target_link_libraries(my-test PRIVATE ApprovalTests::ApprovalTests)
```
This links to our current setup of ApprovalTests when using ```add_subdirectory```.
```cmake
add_subdirectory(ApprovalTests)
add_executable(my-test PRIVATE main.cpp)
# Notice the target name is different. This requires the user to change the library name.
target_link_libraries(my-test PRIVATE ApprovalTests)
```

This links to our current setup of ApprovalTests when using ```add_subdirectory``` after adding an aliased target.
```cmake
add_subdirectory(ApprovalTests)
add_executable(my-test PRIVATE main.cpp)
# Target name is the same and this requires no change by the user.
target_link_libraries(my-test PRIVATE ApprovalTests::ApprovalTests)
```

Aliasing the ApprovalTests library in CMake is as simple as adding the following somewhere after defining the ```ApprovalTests``` interface library, probably in the same directory where it is defined.
```cmake
add_library(ApprovalTests::ApprovalTests ALIAS ApprovalTests)
```

**Comment by claremacrae** [comment]
I'd been wondering whether to add an aliased target - this is a good understanding of one reason to do so...

Another reason I was aware of is that in `target_link_libraries()`, CMake won't warn if `ApprovalTests` is not found, but it will warn if an library alias isn't found - so that's kinder to users...

**Comment by athrun22** [comment]
@claremacrae Right you are! I use alias libraries internally for this very reason.

**Comment by claremacrae** [comment]
@jwillikers, does the above change look OK? Any feedback on the documentation change? Many thanks.
